#pragma once
#include <Arduino.h>
#include "SessionStore.h"
#include "../track/LapTimer.h"

// Retroactive reconstruction of sessions from GPX files generated by
// this app itself (old races without a .ses).
//
// Race: the GPX starts recording the moment the start is marked, so the
// 1st point is the start line; the direction comes from the first points
// (>= 8 m of displacement). The file is reprocessed through the same
// LapTimer as the live session.
//
// Trip: distance/duration/speeds recomputed from the points
// (speed read from the <speed> tag written by the app).

class GpxImport {
public:
    // file = .gpx name (without directory). Fills out and writes the .ses.
    static bool importRace(const char* file, LapTimer& lt, RaceResult& out);
    static bool importTrip(const char* file, TripResult& out);

private:
    static bool parsePoint(const char* line, double& lat, double& lon,
                           float& speedKmh, uint64_t& epochMs);
    static void carFromFilename(const char* file, char* out, size_t n);
};
